_meta:
  type: "roles"
  config_version: 2

# Roles for Hello World extension, roles that extensions would like to add should be ultimately be defined elsewhere
extension_hw_greet:
  reserved: true
  cluster_permissions:
    - 'hw:greet'

legacy_hw_greet_with_name:
  reserved: true
  cluster_permissions:
    - 'cluster:admin/opensearch/hw/greet_with_name'

extension_hw_full:
  reserved: true
  cluster_permissions:
    - 'hw:greet'
    - 'hw:greet_with_adjective'
    - 'hw:greet_with_name'
    - 'hw:goodbye'