name: Bulk Integration Test For Sample Resource Plugin

on: [workflow_dispatch]

env:
  GRADLE_OPTS: -Dhttp.keepAlive=false

jobs:
  bulk-integration-test-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [21]

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}

      - uses: actions/checkout@v4

      - run: OPENDISTRO_SECURITY_TEST_OPENSSL_OPT=true ./gradlew :sample-resource-sharing-plugin:integrationTest

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.jdk }}-${{ matrix.test-file }}-sample-resource-sharing-reports
          path: |
            ./sample-resource-sharing-plugin/build/reports/

      - name: check archive for debugging
        if: always()
        run: echo "Check the artifact ${{ matrix.jdk }}-${{ matrix.test-file }}-sample-resource-sharing-reports.zip for detailed test results"
